name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install application dependencies
      run: npm ci

    - name: Build server with coverage
      run: npm run build-coverage

    - name: Install test dependencies
      run: npm ci
      working-directory: tests-e2e

    - name: Install Playwright browsers
      run: npx playwright install --with-deps
      working-directory: tests-e2e

    - name: Run server with coverage
      run: npm run start-coverage &

      env:
        CI: true

    - name: Run Playwright tests
      run: npm test
      working-directory: tests-e2e
      env:
        CI: true

    - name: Setup LCOV
      uses: hrishikesh-kadam/setup-lcov@v1

    - name: Report code coverage
      uses: zgosalvez/github-actions-report-lcov@v3
      with:
        coverage-files: coverage/lcov.*.info
        minimum-coverage: 90
        artifact-name: code-coverage-report
        github-token: ${{ secrets.GITHUB_TOKEN }}
        working-directory: apps/my-first-app
        update-comment: true

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: tests-e2e/playwright-report
        retention-days: 30
